### PR TITLE
Don't use --no-dangling with old git versions

### PR DESCRIPTION
**Pull request by rubiojr**
`--[no-]dangling` was added to Git 1.7.10.

/cc @github/backup-utils

### CODE REVIEW

**Comment by gnawhleinad** [comment]
LGTM!

**Comment by rubiojr** [comment]
Doesn't work very well if git man pages are not available, so needs better detection. Trying to avoid parsing git version though.

**Comment by rubiojr** [comment]
Although a properly packaged git will include them, so changed my mind. The downside is that we'll end up not using `--no-dangling` even if it's available, so it's not that bad.

**Comment by rubiojr** [comment]
Ended up using `-h` instead of `--help` as suggested by @snh, so `git` doesn't need the man pages installed.

**Pull request merged**
