### PR TITLE
Add usage instructions for user-facing commands

### PR DESCRIPTION
**Pull request by cs-shadow**

### CODE REVIEW

**Comment by rubiojr** [comment]
Thanks @cs-shadow, let me have a closer look at this.

**Comment by cs-shadow** [comment]
Hi @rubiojr! If there's anything else that you need from my side, please let me know :)

**Comment by rubiojr** [comment]
Hey @cs-shadow, thanks.

We're currently evaluating if we should rewrite argument parsing. There's some argument parsing code in `ghe-backup-config` (https://github.com/github/backup-utils/blob/master/share/github-backup-utils/ghe-backup-config#L28-L39 and https://github.com/github/backup-utils/blob/master/share/github-backup-utils/ghe-backup-config#L28-L39) that we want to move to the front-end scripts (ghe-backup and ghe-restore). It's currently confusing people and causing some minor UX issues.

You can either help us to get there (much appreciated 😉) or wait a bit for us to figure out a proper cross-platform strategy to parse arguments and incorporate your changes.

/cc @taz

**Comment by cs-shadow** [comment]
Hi @rubiojr, I agree that current argument parsing is slightly confusing and also threw me off the first time I was looking at it. I'll be happy to help make it clearer.

Is the plan to simply move the argument parsing code mentioned above to these scripts or is it to rewrite the logic as well?

**Comment by taz** [comment]
Hi @cs-shadow!

> Is the plan to simply move the argument parsing code mentioned above to these scripts or is it to rewrite the logic as well?

Currently the plan is for a little bit of both. Apologies for the delay on this. I'm hoping to have a PR up for it this week. 

I'm incorporating the suggestions you've made here too, so I'll absolutely be pinging you for feedback once it's ready.

**Comment by cs-shadow** [comment]
Hi @taz. That sounds good to me. Let me know if you need any help in writing or reviewing this, I'd be happy to help.

**Comment by cs-shadow** [comment]
Closing this PR as these changes were incorporated in 64648155e157a28a806ce639ff797fc46ee76b75

**Comment by taz** [comment]
Hi @cs-shadow, thanks for checking in and closing this. My apologies that it took so long to get to this point. 

I just need to finish adding a couple of new tests, then I'll raise a PR and get a review from you if that's 🆒 ?

**Comment by cs-shadow** [comment]
@taz Sure, I'll be happy to review the changes. Just @mention me in the PR

**Pull request closed without merging**
