### PR TITLE
Fix ghe-backup-config test flakiness

### PR DESCRIPTION
**Pull request by snh**
Updates the _ghe-backup-config test_ so that it stores the `ghe-backup-config` output in a variable.

This appears to resolve the flakiness this test experiences on OS X.

/cc @github/backup-utils

### CODE REVIEW

**Comment by snh** [comment]
I first noticed this flakiness on the Travis OS X builds, but have also been able to reproduce locally on OS X.

Master:

```
bash-3.2$ ./test/test-ghe-backup-config.sh
test: ghe-backup-config GHE_CREATE_DATA_DIR disabled ... ...                    FAILED
    + set -e
    + export GHE_DATA_DIR=/tmp/backup-utils/test/tmp/test-ghe-backup-config.sh-24950/create-enabled-data
    + GHE_DATA_DIR=/tmp/backup-utils/test/tmp/test-ghe-backup-config.sh-24950/create-enabled-data
    + . share/github-backup-utils/ghe-backup-config
    + grep -q 'Creating the backup data directory ...'
    + test -d /tmp/backup-utils/test/tmp/test-ghe-backup-config.sh-24950/create-enabled-data
    test failed. last command exited with 1
test: ghe-backup-config ssh_host_part ...                          OK
test: ghe-backup-config ssh_port_part ...                          OK
test: ghe-backup-config ghe_parse_remote_version v11.10.x series ... OK
test: ghe-backup-config ghe_parse_remote_version v2.x series ...   OK
```

This branch:
```
bash-3.2$ ./test/test-ghe-backup-config.sh
test: ghe-backup-config GHE_CREATE_DATA_DIR disabled ...           OK
test: ghe-backup-config ssh_host_part ...                          OK
test: ghe-backup-config ssh_port_part ...                          OK
test: ghe-backup-config ghe_parse_remote_version v11.10.x series ... OK
test: ghe-backup-config ghe_parse_remote_version v2.x series ...   OK
```

**Comment by rubiojr** [comment]
@snh not sure about this, the condition failing here is `test -d $GHE_DATA_DIR` and this fix doesn't really explain why it only affects macOS.

**Comment by rubiojr** [comment]
@snh I think I added the right fix in 218ff46. Still not clear to me how this test ever worked though.

**Comment by rubiojr** [comment]
Just found https://travis-ci.org/github/backup-utils/jobs/176685416, proving that the problem is not macOS specific also.

**Pull request merged**
