### PR TITLE
Added basic timing around the ghe-restore process

### PR DESCRIPTION
**Pull request by johnclaus**
This PR adds basic timing output around the `ghe-restore` process, per the request from Issue #529

### CODE REVIEW

**Comment by cainejette** [comment]
Awesome, thank you!

**Comment by johnclaus** [comment]
@cainejette My PR is failing on linters erroring out on code I didn't change.  Is there any way of running these linters locally against my change?

**Comment by cainejette** [comment]
> My PR is failing on linters

That shouldn't be a required step, so you should be clear from that perspective. Although we realize now that the action wasn't set up properly to trigger on PRs from forks. If you push a commit, will that trigger the two required build steps?

**Comment by johnclaus** [comment]
> If you push a commit after that goes in, will that trigger the two required build steps?

Yes.  It seems to pass the [macos-latest](https://github.com/johnclaus/backup-utils/runs/946384416) step, but it fails on [ubuntu-latest](https://github.com/johnclaus/backup-utils/runs/946384405) and [Lint Code Base](https://github.com/johnclaus/backup-utils/runs/946384385).

The former error seems to be because of an outdated URI for downloading `shellcheck` and the latter appears to fail on Markdown linting errors unrelated to my PR.

**Comment by cainejette** [comment]
> The former error seems to be because of an outdated URI for downloading `shellcheck`

This is also being fixed in #628 

> the latter appears to fail on Markdown linting errors unrelated to my PR.

This can be ignored

**Comment by johnclaus** [comment]
@cainejette So can someone merge this or is there something else I need to do for this PR to go green?

**Comment by cainejette** [comment]
> can someone merge this

Yep! We will see it through. Thanks for contributing!

**Comment by cjonsmith** [comment]
Merged! Sorry for the delay, and thanks again for the contribution 😄

**Pull request merged**
