### PR TITLE
Bump version: 3.2.0.rc1

### PR DESCRIPTION
**Pull request by bwestover**
Includes general improvements & bug fixes and support for GitHub Enterprise Server v3.2.0.rc1
* Leaked host key check: Avoid false positives from FIPS mode #748
* Always restore user-password-secrets #762
* Make some of the actions setting best effort #767
* Remove reference to `ghe-cluster-cleanup-nodes` #768
* Stop/Restart Actions in ghe-restore #769
* Clear GitHub Connect settings when not restoring settings #770
* GitHub Connect Reset Issue #776

/cc @github/backup-utils

### CODE REVIEW

**Review by Jcsenterprisesllc — COMMENTED** [review]
app

**Comment by Cristiano1226** [comment]
Favo sair do telegone

Em sex, 10 de set de 2021 17:10, Brett Westover ***@***.***>
escreveu:

**Comment by Shazcarrera96** [comment]
Yupi2

**Comment by Shazcarrera96** [comment]
Boon Seng Kaw...??
Boon Ah Heong 😉
Yamm Sengg

**Comment by Shazcarrera96** [comment]
Yu bow hun ??
Sa lax Hunnnnn Hommia,
Ah Seng Ciak la..., CiakbowCiak ..??

**Pull request merged**
