### PR TITLE
Bump version: 3.1.0

### PR DESCRIPTION
**Pull request by zachary-mark**
Includes general improvements & bug fixes and support for GitHub Enterprise Server v3.1.0

/cc @github/backup-utils

### CODE REVIEW

**Comment by Alexocool** [comment]
wwwwww

**Review by Alexocool — CHANGES_REQUESTED** [review]
@Alexocool

**Comment by Alexocool** [comment]
- Fhh do of BJJ trump hc vs eh@mislav

**Comment by Shazcarrera96** [comment]
.

**Review by JessicaSpaInspector — COMMENTED** [review]
Hi

**Comment by sami9v** [comment]
Bh

**Review by sami9v — COMMENTED** [review]
Vg

**Review by sami9v — COMMENTED** [review]
Gvr

**Comment by Shazcarrera96** [comment]
Ulu2 tani yellek ne

**Pull request merged**
