### PR TITLE
Update repository backups to use ghe-gc-* for lock file management

### PR DESCRIPTION
**Pull request by snh**
Updates the repository backup scripts to use the `ghe-gc-enable` and `ghe-gc-disable` scripts for managing the `.sync_in_progress` lock file.

These were introduced in #179 and are already used by the restore equivalents.

/cc @github/backup-utils

### CODE REVIEW

**Comment by rubiojr** [comment]
Nice. My plan is to skip this for the next patch release and include the refactor in the next minor though, if that sounds good.

**Comment by snh** [comment]
@rubiojr Sounds good. I have a few other PR's landing soon that are also non-urgent and are best left until the next minor.

**Comment by rubiojr** [comment]
:shipit:

**Review by matznermatzner — APPROVED** [review]

**Review by matznermatzner — APPROVED** [review]

**Comment by nazarmaddin** [comment]
#188

**Comment by ayeshasiddika9196** [comment]
unlock

**Comment by monsothin96** [comment]
#188

**Pull request merged**
