### PR TITLE
fixed the problem that memory overflows when there are too many files…

### PR DESCRIPTION
**Pull request by Kiyokazu-g**
im reporting this issue in support ticket( #1380328 ).

---
Fix such an error:

```
Restoring storage data ...
/data/user/_ghe_backup/backup-utils/share/github-backup-utils/ghe-restore-storage: xrealloc: cannot allocate 18446744072682251136 bytes
````

### CODE REVIEW

**Review by sultanaha — APPROVED** [review]

**Review by domofactor — DISMISSED** [review]

**Comment by Kiyokazu-g** [comment]
@domofactor

Hi! i have fixed this warnings from ubuntu build, but should i also support macos?

https://github.com/github/backup-utils/pull/804/commits/af5ef890295258db93c9bba36f93b4ea8fdaabb9

https://github.com/github/backup-utils/runs/4453309459?check_suite_focus=true#step:5:56
https://github.com/github/backup-utils/runs/4453309511?check_suite_focus=true#step:5:97


>Not yet
https://github.com/github/backup-utils/runs/4453309545?check_suite_focus=true

**Comment by domofactor** [comment]
thanks @Kiyokazu-g 👋  

そのエラーは多分関係ないと思いますのでまた別のPRで直しますね 😄 

it looks like the macos build is broken for something unrelated. so, we can fix that later in a separate PR 👍

**Comment by Kiyokazu-g** [comment]
@domofactor 🥞  thanks! 🥞 

most recent build also failed, so im checking, but it doesn't seem to be related to this PR...? github-timerd(consul)?
if there is anything i should do, anything at all, just let me know.

**Comment by domofactor** [comment]
@Kiyokazu-g hmmm, yeah that ubuntu tests should be passing. 🤔  i'll take a look tomorrow see what's going on.

**Comment by domofactor** [comment]
@Kiyokazu-g it looks like failure for the ubuntu tests are actually related to your change.

```
test: ghe-restore allows restore of external DB snapshot to external DB instance ... ... FAILED (11s)
```

can you update/fix the test as well over in https://github.com/Kiyokazu-g/backup-utils/blob/master/test/test-ghe-restore-external-database.sh#L47. thanks! 🙏

**Comment by Kiyokazu-g** [comment]
@domofactor

its hard to tell because there are too many logs, but i modified it and checked it in my environment.

this doesn't have much to do with my changes, should I write an additional test?
> https://github.com/Kiyokazu-g/backup-utils/blob/master/test/test-ghe-restore-external-database.sh#L47

**Comment by domofactor** [comment]
@Kiyokazu-g great, thanks! 🙏  I don't think you need to add any additional tests, i'll try re-running them.

**Comment by Kiyokazu-g** [comment]
hmmm...
I'm sorry for making you run it so many times, I'll check it again carefully.

https://github.com/github/backup-utils/runs/4469512348?check_suite_focus=true#step:5:487

**Comment by Kiyokazu-g** [comment]
i have modified it to more correctly follow contents of shellcheck and correctly write to the file.
restore should work!

https://github.com/koalaman/shellcheck/wiki/SC2038

@domofactor plz rerun when you have time!

**Comment by Kiyokazu-g** [comment]
@manue1 Thanks for rerun!

**Review by domofactor — APPROVED** [review]

**Comment by Kiyokazu-g** [comment]
thx all!

**Pull request merged**
