### PR TITLE
Fix and make its Debian package modern

### PR DESCRIPTION
**Pull request by henrich**
With the power of lintian, lintian-brush, and my DD experience, fix all lintian warnings for the deb package (bonus: add man pages).

And also fix this package as arch-indep package (arch: amd64 -> arch: all). It means we can install this package on arm64 hosts without a rebuild.

### CODE REVIEW

**Comment by henrich** [comment]
Note: a test failure on macos-latest is fixed with #733 (more strict shellcheck behavior since ubuntu-* env use v0.7.0 but macos env uses latest 0.7.2).

**Comment by henrich** [comment]
Hmm, macos-latest failed with another issue

> test: ghe-restore -c into unconfigured vm ... ...                               FAILED (15s)

Of course, it is not related to this PR and merged shellcheck fix PR :)

**Review by zachary-mark — COMMENTED** [review]
Apologies for the delay on reviewing this pull request!  We were in the process of getting 3.1.0 GAed and this fell a bit by the wayside.

This looks awesome!  I've hit the button to merge `master` into this PR and if everything passes I will give this one last look before approval - I tried it out myself on a stretch system that I use on a regular basis and things seem to be working correctly.

**Review by zachary-mark — APPROVED** [review]
I'm re-running the CI now, but I'm pretty sure you didn't cause the OSX failure.  Nice work on this and I love the help2man addition.  Thank you for your contribution!

**Review by t2GreenFamidam — COMMENTED** [review]
Done

**Pull request merged**
