### PR TITLE
trap INT for ghe-backup-repository cleanup

### PR DESCRIPTION
**Pull request by jianghao0718**
## Context
In `ghe-backup-repositories` we missed cleanup for INT (say user uses ctrl+c) which will block repo maintenance job to run on appliances. In this PR, we did following
- trap INT for `ghe-backup-repositories` 
- add more loggings when `ghe-enable-gc` fails

/cc @snh @ryanfolsom @darostegui

### CODE REVIEW

**Review by zachary-mark — APPROVED** [review]
Looks reasonable!

**Review by ryanfolsom — APPROVED** [review]
LGTM!

**Comment by herewegoagain2** [comment]
> ## Context
> 
> In `ghe-backup-repositories` we missed cleanup for INT (say user uses ctrl+c) which will block repo maintenance job to run on appliances. In this PR, we did following
> 
> - trap INT for `ghe-backup-repositories` 
> 
> - add more loggings when `ghe-enable-gc` fails
> 
> 
> 
> /cc @snh @ryanfolsom @darostegui 
> 
> 
> 
> 
> 
>

**Review by herewegoagain2 — COMMENTED** [review]
- [ ] @herewegoagain2

**Pull request merged**
